# This is a generated file. Not intended for manual editing.
services:
  nutrifitlogbackend.api:
    build:
      context: "C:\\NutriFitLogApp\\NutriFitLogBackend"
      dockerfile: "NutriFitLogBackend.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/NutriFitLogBackend.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "nutrifitlogbackend.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\megas\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\NutriFitLogApp\\NutriFitLogBackend\\NutriFitLogBackend.Api:/app:rw"
    - "C:\\NutriFitLogApp\\NutriFitLogBackend:/src:rw"
    working_dir: "/app"
